Update Proposed-WG-WebIdentityCredentials.md
fedidcg/fedidcg.github.io pull request #21
Opened 2023-12-06 17:31 UTC by hlflanagan

Revised based on horizontal review, direct feedback

2023-12-06 17:41 UTC, samuelgoto approved these changes
LGTM

2023-12-06 17:41 UTC, samuelgoto commented on charters/Proposed-WG-WebIdentityCredentials.md
> +- Web platform tests
```suggestion
- Web Platform Tests 
```

WPTs is a well-known acronym, so figured that it would be useful to capitalize

2023-12-13 17:19 UTC, asr-enid approved these changes

2023-12-13 22:44 UTC, TallTed requested changes

2023-12-13 22:44 UTC, TallTed commented on charters/Proposed-WG-WebIdentityCredentials.md
> +The *W3C Federated Identity Working Group* will develop living standard specifications defining an API that allows websites to request a federated identity credential or assertion with the purpose of
```suggestion
The *W3C Federated Identity Working Group* will develop living standard specifications defining an API that allows websites to request a federated identity credential or assertion with the purpose of authenticating a user and/or requesting a set of claims in a way compatible with OIDC or SAML.
```

2023-12-13 22:44 UTC, TallTed commented on charters/Proposed-WG-WebIdentityCredentials.md
> +# PROPOSED Federated Identity Working Group Charter
Perhaps should change the title of this PR to match the above?

2023-12-13 22:44 UTC, TallTed commented on charters/Proposed-WG-WebIdentityCredentials.md
> +
It's worth noting that the [WebID CG](https://www.w3.org/community/webid/) is aiming to charter a WebID WG in the near future, so it's good that this group's proposed name is changing from _Web Identity Credentials_ to _Federated Identity_. Also, the WebID CG/WG work should be kept in mind as complementary and/or conflicting and/or redundant, etc., depending on overall timing....

2023-12-19 14:01 UTC, timcappalli approved these changes
LGTM based on discussions on the recent CG calls

2023-12-19 17:52 UTC, merged